### ISSUE TITLE
Reading Properties with float type

### ISSUE THREAD

**Issue by jboelter007** [SolidEdgeCommunity/SolidEdge.Community.Reader#2]
Testing on 64 Bit Windows 7 I found that reading file properties with float type do not return the saved values.
After some investgation I found the error in GetDataBytes() in Structures.cs
My solution is tested only on 64 Bit:
    private byte[] GetDataBytes()
        {
            var ret = new byte[IntPtr.Size + sizeof(int)];

```
        if (IntPtr.Size == 4)
        {
           BitConverter.GetBytes(p.ToInt32()).CopyTo(ret, 0);
        }
        else if (IntPtr.Size == 8)
        {
           BitConverter.GetBytes(p.ToInt64()).CopyTo(ret,0);
        }
        BitConverter.GetBytes(p2).CopyTo(ret, IntPtr.Size);

        return ret;
    }
```

**Comment by jlnewell** [comment]
Thanks for the heads up. I'll take a look at it and get a build out.

**Comment by jlnewell** [comment]
Version 1.8.0 has been published to NuGet. Thanks for finding and solving the issue.

**Comment by jlnewell** [comment]
Closing old issue.
