### ISSUE TITLE
Opening Document to Read Properties

### ISSUE THREAD

**Issue by Saran88** [SolidEdgeCommunity/SolidEdge.Community.Reader#3]
When opening a document to read properties, I am trying to use the SolidEdgeCommunity.Reader.SolidEdgeDocument.Open method but it is requiring that the file is not already open and it opens the file as write. I tried to use a STREAM of the file instead but when trying to get the PropertySet, I get 
"Unable to cast object of type 'SolidEdgeCommunity.Reader.Native.ReadOnlyIStorage' to type 'SolidEdgeCommunity.Reader.Native.IPropertySetStorage'."

Is there something wrong here or can we not read an already opened file with Community.Reader?

Code with FileStream:
using (var fs = new FileStream(fileLocationPath, FileMode.Open, FileAccess.Read))
            {
                var document = SolidEdgeCommunity.Reader.SolidEdgeDocument.Open(fs);
                var propertySets = document.PropertySets;
}

**Comment by jlnewell** [comment]
I agree. You should be able to call SolidEdgeCommunity.Reader.SolidEdgeDocument.Open() on a file that is currently open in Solid Edge. I'll dig into it and see if I can get it fixed. Thanks for letting me know.

**Comment by jlnewell** [comment]
I have a fix for both issues that you've raised and am in the process of testing.

**Comment by Saran88** [comment]
Awesome, thanks Jason.

**Comment by jlnewell** [comment]
Published 2.0.0 to NuGet. Update your package reference and see how it goes. Thanks.

**Comment by jlnewell** [comment]
Closing old issue.
